### ISSUE TITLE
If someone had autologin enabled for their account previously it may no longer work afterwards, they'll have to set it up again.

### ISSUE THREAD

**Issue by Evernow** [Evernow/AutoDDU_CLI#11]

**Comment by Arron17** [comment]
I don't believe there is any real way around this. Because you change the autologin to the DDU User it removes the current autologin.
In order to setup autologin you need the users account password.

You could potentially try using this https://docs.microsoft.com/en-us/sysinternals/downloads/autologon and have the user enter their credentials, but it doesn't verify the credentials, so if the user enters them incorrectly they might cause themselves problems.

There's no easy way to do something like store the password before the DDU user is created as it's encrypted as an LSA Secret in registry. You can decrypt it, but that would be a bad idea for something like this in my opinion. https://devblogs.microsoft.com/scripting/use-powershell-to-decrypt-lsa-secrets-from-the-registry/

If you want to go into it, I believe this is where the Current Password is stored "HKEY_LOCAL_MACHINE\SECURITY\Policy\Secrets\DefaultPassword\CurrVal" however it needs System Privledges to be accessed. You could potentially save that key and then reimport it along with updating the user values in "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon"

AutoAdminLogon = 1
AutoLogonSID
DefaultDomainName
DefaultUserName

**Comment by Evernow** [comment]
Fixed with https://github.com/Evernow/AutoDDU_CLI/commit/2aadc476e652f59d8ec6584c6e45cbbfe61a31e6
